config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'terms',    to: 'home#terms'
  get 'privacy',  to: 'home#privacy'
  get 'bootcamp', to: 'home#bootcamp'

  namespace :mastery do
    get 'data-science'
    get 'devops'
    get 'cybersecurity'
    get 'microservices'
    get 'digital-leadership'
    get 'scrum'
  end

  root 'home#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program
  attr_reader :name,
              :description

  def initialize(name:, description:)
    @name        = name
    @description = description
  end
end

app/models/quote.rb
class Quote
  attr_reader :text,
              :name,
              :title,
              :company
              
  def initialize(text:, name:, title:, company:)
    @text    = text
    @name    = name
    @title   = title
    @company = company
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @quote_a = Quote.new(
      text:    'El <b>Mastery Program</b> de <b>Data Science</b> no sólo fue una excelente opción para adquirir conocimiento, sino que al ser práctico, nos ayudó a desmitificar conceptos de Inteligencia Artificial, Machine Learning y Data Science. Definitivamente recomendable al 100 por ciento.',
      name:    'Alfredo Pequeño',
      title:   'Chief Data Officer',
      company: 'Banregio'
    )

    @quote_b = Quote.new(
      text:    'El <b>Mastery Program</b> en <b>DevOps</b> fue una excelente oportunidad de tener un acercamiento directo con conceptos y tecnologías que desconocía como implementar en mis proyectos. Además, los instructores tienen una basta experiencia en las tecnologías que enseñan. Sin duda, una certificación 100% recomendable.',
      name:    'Alfonso Banda',
      title:   'Full Stack Developer',
      company: 'Blue People'
    )
  end

  def terms
  end

  def privacy
  end

  def bootcamp
    @quote = Quote.new(
      text:    'Creemos en un futuro donde la educación de calidad no sea un privilegio: donde lo única diferencia entre personas no sea su nivel socioeconómico sino su talento y su pasión para cambiar el mundo.',
      name:    'Jorge Téllez',
      title:   'Director General',
      company: 'CeroUno'
    )
  end
end

app/controllers/mastery_controller.rb
class MasteryController < ApplicationController
  def data_science
    @program = Program.new(
      name: 'Data Science',
      description: 'Aprende a modelar y estructurar datos, desarrollar modelos estadísticos, utilizar machine learning y crear visualizaciones para guiar a las organizaciones al futuro.'
    )

    @quote = Quote.new(
      text:    'El <b>Mastery Program</b> de <b>Data Science</b> no sólo fue una excelente opción para adquirir conocimiento, sino que al ser práctico, nos ayudó a desmitificar conceptos de Inteligencia Artificial, Machine Learning y Data Science. Definitivamente recomendable al 100 por ciento.',
      name:    'Alfredo Pequeño',
      title:   'Chief Data Officer',
      company: 'Banregio'
    )
  end

  def devops
    @program = Program.new(
      name: 'DevOps',
      description: 'Aprende a reducir los tiempos de despliegue, versionar y contenerizar aplicaciones, y orquestar y monitorear microservicios para administrar infraestructura programáticamente.'
    )

    @quote = Quote.new(
      text:    'El <b>Mastery Program</b> de <b>Cybersecurity</b> me permitió reforzar y comprender las diferentes soluciones de seguridad y detectar las principales amenazas informáticas y vulnerabilidades de infraestructura. Recomiendo ampliamente el programa ya que cuentan con instructores muy capacitados y conocen a la perfección las diferentes amenazas actuales.',
      name:    'Jorge Martínez',
      title:   'Jefe de Soporte y Comunicación',
      company: 'Autlán'
    )
  end

  def cybersecurity
    @program = Program.new(
      name: 'Cybersecurity',
      description: 'Aprende a evaluar vulnerabilidades, hackeo ético, ingeniería social, seguridad en la nube y gestión de políticas de ciberseguridad para proteger a las organizaciones de ciberataques.'
    )

    @quote = Quote.new(
      text:    'El <b>Mastery Program</b> de <b>Cybersecurity</b> me facilitó el aprendizaje de herramientas que nos ha permitido elevar la calidad y la eficiencia del despliegue productivo de las aplicaciones que desarrollamos en la organización. Recomiendo ampliamente el programa.',
      name:    'Rafael Quintero',
      title:   'Líder de Equipo de DevOps',
      company: 'Helicon'
    )
  end

  def microservices
  end

  def digital_leadership
  end

  def scrum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bootcamp.html.slim
.leader
  .row
    .col
      = link_to root_path do
        = image_tag 'cerouno-logo-horizontal.png', width: "200", alt: "CeroUno Logo"
      h1 Descubre tu<br> Potencial
      h3 Aprende a programar en 24 semanas y<br> <b>te conseguimos empleo</b>. Clases en línea<br> con instructores, en vivo, y mentoría<br> con los mejores expertos de la industria.
      = link_to 'APLICA AHORA', 'https://cerouno.typeform.com/to/Ro3MyJ', class: 'btn btn-lg btn-primary'

.difference
  .row
    .col-md-8
      h2 Aprende a Programar.<br> Duplica tu Sueldo.
    .col-md-4
      p Los programas de <b>CeroUno</b> están diseñados alrededor de tu éxito. Una carrera en programación te permite duplicar tus ingresos. ¿Lo mejor de todo? Tenemos relación con más de 50 empresas que están buscando desarrolladores como tú.
  hr
  .row
    .col-md-4.center
      i.far.fa-user-headset.fa-3x
      h3.bold Clases en Vivo
      p Olvídate de las clases obsoletas. Los programas de <b>CeroUno</b> son impartidos en línea por instructores en vivo. Además, puedes recibir mentoría directa de CTOs y Senior Developers con años de experiencia en la industria.
    .col-md-4.center
      i.far.fa-briefcase.fa-3x
      h3.bold Asistencia Laboral
      p Tu éxito profesional es lo más importante. Nosotros tenemos a un equipo dedicado a conseguirte oportunidades de empleo de calidad, pasar tus entrevistas técnicas y negociar tu primer sueldo en la industria de tecnología.
    .col-md-4.center
      i.far.fa-hand-holding-usd.fa-3x
      h3.bold Sin Deuda
      p Empieza tu carrera como programador sin deuda y sin intereses. Con nuestros <b>Acuerdos de Ingreso Compartido</b> paga sólo 999 pesos al mes hasta que tengas un trabajo y percibas más de 16 mil pesos netos al mes.
.photo
  .row.no-gutters
    .col-md-8
      = image_tag 'students-1.jpg', width: "100%", alt: "Student looking upwards"
    .col-md-4.no-gutters
      .col-md-12
        = image_tag 'students-2.jpg', width: "100%", alt: "Founder addressing class"
      .col-md-12
        = image_tag 'students-3.jpg', width: "100%", alt: "Students sitting and paying attention"
= render 'layouts/testimony', quote: @quote
.programs
  .row.top
    .col-md-4
      h2 Programa
    .col-md-8
      p Durante este programa aprenderás a desarrollar aplicaciones web completas utilizando JavaScript, el lenguaje de programación más usado del mundo. Al graduarte de este programa, te sentirás cómodo creando aplicaciones en Node.js y React, utilizarás el control de versiones para colaborar con otros desarrolladores y podrás convertir necesidades de negocio en productos digitales.
  .row
    .col-md-2.center.offset-md-4
      h5.lighter Semanas
      h3.highlight 1-6
    .col-md-6.center
      h5.lighter Módulo 1
      h3.highlight Fundamentos Web
      p Aprende a desarrollar páginas web básicas con HTML, CSS y JavaScript. Durante este módulo, aprenderás a utilizar herramientas básicas de desarrollo como implementación de control de versiones, uso de la terminal y manejo del editor de texto.
  .row.second
    .col-md-2.center.offset-md-4
      h5.lighter Semanas
      h3.highlight 7-12
    .col-md-6.center
      h5.lighter Módulo 2
      h3.highlight Desarrollo Front-End
      p Aprende a crear aplicaciones de una sóla página con React, Redux, React Router y AJAX. Durante este módulo, aprenderás a guardar datos en los diferentes elementos de HTML y a responder a las interacciones de usuarios desde tu página web.
  .row.second
    .col-md-2.center.offset-md-4
      h5.lighter Semanas
      h3.highlight 13-18
    .col-md-6.center
      h5.lighter Módulo 3
      h3.highlight Desarrollo Back-End
      p Aprende a crear aplicaciones back-end escalables con Node.js. Durante este módulo aprenderás a crear aplicaciones Back-End que exponen APIs web para conectarse con aplicaciones Front-End construídas en React.
  .row.second
    .col-md-2.center.offset-md-4
      h5.lighter Semanas
      h3.highlight 19-24
    .col-md-6.center
      h5.lighter Módulo 4
      h3.highlight Pensamiento Algorítmico
      p Aprende a pensar como un ingeniero de software. Durante este módulo resolveremos problemas de computación como algorítmos de ordenamiento, implementaciones de listas vinculadas o un árbol de búsqueda binaria.
= render 'layouts/companies'
.financing
  .row
    .col-md-8
      h2 Financiamiento
    .col-md-4
      p  La falta de recursos económicos no será un impedimento para cambiar tu vida. Tenemos tres maneras de financiar el inicio de tu carrera como desarrollador de software profesional: <b>Acuerdo de Ingreso Compartido</b>, <b>Meses sin Intereses</b> o <b>Pago de Contado</b>.
  .hr
  .row
    .col-md-4.center
      i.far.fa-handshake-alt.fa-3x
      h3.bold Ingreso Compartido
      p Paga sólo 999 pesos al mes hasta que tengas un trabajo con un sueldo 16 mil pesos neto mensual. Después de eso, paga 15 por ciento de tu sueldo neto por 36 meses. Así nosotros compartimos el riesgo contigo.
    .col-md-4.center
      i.far.fa-credit-card.fa-3x
      h3.bold Meses sin Intereses
      p Si buscas una opción de financiamiento tradicional, puedes cubrir el monto de tu colegiatura en hasta 36 mensualidades sin intereses de 1 mil 999 pesos al mes mediante debitación automática.
    .col-md-4.center
      i.far.fa-money-check-edit-alt.fa-3x
      h3.bold Pago de Contado
      p El monto completo de la colegiatura del programa es de 69 mil 990 pesos, pero si pagas de contado, recibe un descuento de 5 mil pesos sobre el monto total de la colegiatura y paga sólo 64 mil 990 pesos.
= render 'layouts/instructors'

app/views/home/privacy.html.slim
section.static
  .col-md-12
    markdown:
      # Aviso de Privacidad

      **CeroUno VENTURES SAPI DE CV (“CeroUno”)**, en su carácter de responsable, emite el presente aviso de privacidad (el “Aviso”) en términos de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (la “Ley”), su Reglamento y los Lineamientos del Aviso de Privacidad, para informarle los términos y condiciones sobre la obtención, almacenamiento, uso, divulgación y transferencia (el “Tratamiento”) de sus Datos Personales (según se definen más adelante), que hayan sido o sean entregados a **CeroUno** por clientes, empleados, proveedores, los representantes, apoderados y/o empleados de los mismos (cada uno de ellos en lo personal, el “Titular”), así como los datos que se recaben en virtud  de la relación comercial o de servicios del Titular con **CeroUno**.

      Para efectos del presente Aviso, **CeroUno** señala como su domicilio el ubicado en Europa 305, Contry, Monterrey, Nuevo León (el “Domicilio”). Asimismo, se señala el sitio web http://www.cerouno.io, como el portal de Internet en el cual el Titular tendrá a su disposición el Aviso y que **CeroUno** utilizará para los efectos referidos más adelante en el presente (el “Portal”).

      Los términos del presente Aviso serán observados por **CeroUno** y sus empresas controladoras, afiliadas y subsidiarias (conjuntamente, las “Partes Relacionadas”), así como los encargados y terceros, que realicen cualquier Tratamiento de los datos personales, incluyendo los datos personales financieros.

      ### I. Datos Personales

      Los datos personales del Titular entregados a **CeroUno** (los “Datos Personales”) podrán consistir en: (i) Identidad de la persona (nombre, firma, Registro Federal de Contribuyentes, Clave Única de Registro de Población, fecha de nacimiento, nacionalidad, estado civil, sexo y fotografías e imágenes de video de cámaras de seguridad, entre otros); (ii) Datos de Contacto (domicilio particular, número de teléfono de domicilio, número de celular y correo electrónico personal, entre otros);  (iii) Datos laborales del Titular (Número de Seguridad Social, contratos de trabajo, confirmación de pagos de salarios, confirmación de pagos de cuotas de seguridad social, aviso de altas y bajas ante las instituciones de seguridad social); (iv) Financieros o patrimoniales (número de cuenta bancaria para hacer depósitos, monto del salario actual, su integración y ajustes salariales, entre otros).

      El Titular declara que los Datos Personales que proporcione a **CeroUno**, incluyendo los datos financieros o patrimoniales, serán claros, completos, precisos y actualizados, ello sin perjuicio que **CeroUno** pueda asegurarse de la calidad de los mismos o de que el Titular tenga el derecho de rectificarlos y/o actualizarlos.

      ### II. Finalidades

      El Tratamiento de los Datos Personales del Titular, se realizará para cumplir con cualquiera de las siguientes finalidades que den origen y sean necesarias para la relación comercial que tiene el Titular con **CeroUno**, como: (i) ejercer cualquier derecho o cumplir con las obligaciones derivadas de la relación comercial con **CeroUno**, incluyendo el pago de la contraprestación pactada en un contrato, procedimientos de cobranza, proveer medios necesarios para el cumplimiento de sus funciones, entre otros; (ii) realizar una base de datos, registro y directorio de proveedores y clientes para beneficio y uso interno de **CeroUno**, (iii) cumplir con cualquier legislación aplicable u obligación derivada de la relación comercial con **CeroUno**, así como proporcionar información y documentación a cualquier autoridad gubernamental competente, nacional o extranjera, como parte de algún proceso o para cumplir con algún requerimiento de ley; (iv) dar cumplimiento a auditorías realizadas a **CeroUno** o a sus Partes Relacionadas; (v) confirmar identidad y situación patrimonial del Titular; (vi) brindar acceso a las diversas instalaciones de **CeroUno** a proveedores, clientes, así como a sus empleados, representantes o apoderados legales; (vii) confirmar el cumplimiento de obligaciones de ley por parte del proveedores, clientes respecto de sus empleados; (viii) celebrar contratos con el Titular; y (ix) cumplir con cualquier obligación que se derive de la relación comercial que se establezca entre el Titular y **CeroUno**.

      Cualquier ampliación a las finalidades previamente expuestas deberá ser comunicada por **CeroUno** conforme a las disposiciones del presente Aviso.

      ### III. Consentimiento del Titular

      Al acceder al Portal y/o la suscripción del presente Aviso, el Titular reconoce que ha leído, entiende y acepta los términos del Aviso.

      La no oposición del Titular al Tratamiento de los Datos Personales por los medios establecidos en el Aviso y la entrega de cualesquier Datos Personales a **CeroUno**, ya sea que lo haga de forma directa o a través de un representante o apoderado legal, constituyen en sí mismos un signo inequívoco del consentimiento expreso que el Titular otorga a **CeroUno** para el Tratamiento de los Datos Personales, incluyendo los datos financieros o patrimoniales y para la transferencia de los mismos conforme a lo dispuesto en el presente Aviso, ya sea por **CeroUno**, los encargados, terceros y las Partes Relacionadas, durante el tiempo que sean indispensables para las finalidades previamente expuestas.

      ### IV. Transferencia de Datos Personales

      En virtud del consentimiento otorgado por el Titular, **CeroUno** podrá transferir por cualquier medio los Datos Personales a los siguientes terceros: (1) Partes Relacionadas nacionales y extranjeras, en términos de la Ley, que operan bajo nuestros mismos procesos y políticas internas de protección de datos personales para las finalidades mencionadas en este Aviso; (2) instituciones bancarias para administrar el pago de la contraprestación pactada entre **CeroUno** y el Titular; (3) autoridades gubernamentales competentes (incluyendo judiciales y administrativas) nacionales o extranjeras, para la finalidad a que se refiere el inciso (iii) del apartado de Finalidades del presente Aviso; y (4) cualquier otro tercero de conformidad con las excepciones marcadas en el artículo 37 de la Ley .

      Adicionalmente, **CeroUno** podrá realizar transferencias nacionales o internacionales de los Datos Personales, incluyendo los datos financieros o patrimoniales, a terceros no relacionados, como parte de las siguientes operaciones o transacciones, presentes o futuras, en las que **CeroUno** o sus Partes Relacionadas participen, tales como: i) venta o transferencia de acciones o partes sociales; ii) fusión; iii) consolidación; iv) cambio de control; v) transferencia de activos; vi) reorganización; o vii) liquidación.

      Los terceros receptores de Datos Personales asumirán las mismas obligaciones que correspondan a **CeroUno**.

      ### V. Derechos ARCO

      El Titular tendrá derecho a acceder, rectificar, cancelar u oponerse al Tratamiento de los Datos Personales en cualquier momento sujeto a las disposiciones en la Ley, su Reglamento y cualquier otra disposición aplicable, sin que el ejercicio de sus derechos pueda tener efectos retroactivos o impida a **CeroUno** cumplir con alguna obligación legal, contractual o fiduciaria.

      Para el ejercicio de sus derechos, el Titular realizará su requerimiento por escrito entregado en el Domicilio o vía correo electrónico a la dirección contacto@cerouno.io, dirigiéndose al área responsable de la protección de Datos Personales de **CeroUno**. El escrito que deberá contener como mínimo los requisitos a que se refiere el artículo 29 de la Ley.

      Ante la recepción del escrito, el área responsable de protección de Datos Personales le comunicará al Titular, en el término marcado por la Ley, de su recepción y la determinación respecto a su solicitud. No obstante lo anterior el área responsable de protección de Datos Personales podrá solicitar información adicional para acreditar la personalidad del Titular, así como la documentación que sustente su solicitud y cualquier información adicional que sea necesaria en términos de la Ley para dar contestación a la solicitud de ejercicio de sus derechos.

      ### VI. Revocación de Consentimiento y Limitación de Uso o Divulgación

      El Titular tendrá derecho a revocar su consentimiento del Tratamiento de los Datos Personales o de limitar el uso o divulgación de los mismos en cualquier momento sujeto a las disposiciones en la Ley, su Reglamento y cualquier otra disposición aplicable, sin que el ejercicio de sus derechos pueda tener efectos retroactivos o impida a **CeroUno** cumplir con alguna obligación legal, contractual o fiduciaria.

      Para el ejercicio de la revocación del consentimiento del Tratamiento de Datos Personales o limitar el uso y divulgación de los mismos, el Titular realizará su requerimiento por escrito entregado en el Domicilio o vía correo electrónico a la dirección contacto@cerouno.io, dirigiéndose al área responsable de la protección de Datos Personales de **CeroUno**. El escrito deberá contener como mínimo: i) el nombre del Titular, domicilio y/o correo electrónico para comunicarle la respuesta a su solicitud; ii) los documentos que acrediten la identidad del Titular o en su caso la representación legal del mismo; iii) la descripción clara y precisa de su intención de revocar el consentimiento para el Tratamiento de sus Datos Personales o la descripción precisa sobre el límite del uso o divulgación de los mismos; iv) en caso de ser necesario los documentos que sustenten su solicitud; y v) cualquier elemento o documento que facilite la localización de sus Datos Personales.

      No obstante lo anterior el área responsable de protección de Datos Personales le podrá solicitar información adicional a la descrita anteriormente, para en términos de la ley, dar contestación a la solicitud.

      Ante la solicitud del Titular, el área encargada de Protección de Datos Personales dará respuesta a la misma en un término de veinte (20) días hábiles posteriores a la recepción de la misma. En dicha respuesta se informará al Titular sobre la confirmación de su solicitud o, en su caso, la negativa a la misma por no cumplir con los requisitos establecidos en el presente Aviso.

      ### VII. Cambios al Aviso

      En caso de cualquier cambio a los términos del presente Aviso, los mismos serán comunicados por **CeroUno** por cualquiera de los siguientes medios: (i) envío de correo electrónico a la cuenta que haya proporcionado; (ii) publicación de avisos visibles en las instalaciones de **CeroUno**; o (iii) cualquier otro medio definido de tiempo en tiempo por **CeroUno** y que le permite al Titular tener conocimiento de los cambios en cuestión.

      ### VIII. Medio de Comunicación

      Los proveedores y clientes podrán consultar en cualquier momento este Aviso y sus modificaciones en el Domicilio o solicitándolo al correo electrónico: contacto@cerouno.io.

      ### IX. Contacto

      En caso de cualquier cuestión relacionada con los Datos Personales y el presente Aviso, el Titular se dirigirá con el área responsable de la Protección de Datos Personales ubicado en el Domicilio, o bien, vía correo electrónico a la dirección: contacto@cerouno.io.

      ### X. Legislación Aplicable

      El presente Aviso está sujeto a la legislación aplicable en la República Mexicana.

app/views/home/show.html.slim
.leader
  .row
    .col-md-6.col-left
      = link_to root_path do
        = image_tag 'cerouno-logo-horizontal.png', width: "200", alt: "CeroUno Logo"
      h1 Descubre tu<br> Potencial
      h3 Desarrolla tus habilidades en <b>Data Science</b>, <b>Cybersecurity</b> y <b>DevOps</b>, y lleva tu carrera al siguiente nivel.
      = link_to 'DESCARGA EL TEMARIO', 'https://cerouno.typeform.com/to/OhB7O5', class: 'btn btn-lg btn-primary'
    .col-md-6.col-right

.difference
  .row
    .col-md-4
      h2 Diferencia
    .col-md-8
      p Los programas de <b>CeroUno</b> son la mejor opción para desarrollar tus habilidades o las de tu equipo con líderes expertos en la industria. Nuestros programas están constantemente actualizados y están desarrollados para satisfacer las necesidades de las empresas.
  hr
  .row
    .col-md-4.center
      i.far.fa-briefcase.fa-3x
      h3.bold Experiencia
      p Los programas de <b>CeroUno</b> son impartidos por CTOs y Senior Developers con años de experiencia en la industria.
    .col-md-4.center
      i.far.fa-terminal.fa-3x
      h3.bold Práctico
      p Nuestra clases son prácticas. El contenido de nuestros programas no se encuentran en blogs o tutoriales en línea.
    .col-md-4.center
      i.far.fa-clock.fa-3x
      h3.bold Horario
      p Sabemos que tienes que mantener tu productividad por lo que nuestros programas son fuera de horario laboral.
= render 'layouts/testimony', quote: @quote_a
= render 'layouts/companies'
.programs
  .row.top
    .col-md-4
      h2 Programas
    .col-md-8
      p Nuestra oferta académica incluye tres programas principales: <b>Data Science</b>, <b>DevOps</b>, y <b>Cybersecurity</b>. Estas especializaciones te permitirán desarrollar habilidades prácticas en carreras de alta demanda en la industria de tecnología.
  .row
    .col-md-4.center
      h5.lighter Mastery Program
      h3 Data Science
      p.program-description Aprende a modelar y estructurar datos, desarrollar modelos estadísticos, utilizar machine learning y crear visualizaciones que agreguen valor a tu negocio.
      = link_to 'TEMARIO', mastery_data_science_path, class: 'btn btn-xs btn-primary'
    .col-md-4.center
      h5.lighter Mastery Program
      h3 DevOps
      p.program-description Aprende a automatizar infraestructura, crear pipelines de despligue, contenerizar aplicaciones, monitorear aplicaciones y orquestar infraestructura programáticamente.
      = link_to 'TEMARIO', mastery_devops_path, class: 'btn btn-xs btn-primary'
    .col-md-4.center
      h5.lighter Mastery Program
      h3 Cybersecurity
      p.program-description Aprende a realizar pruebas de penetración, detectar vulnerabilidades en tus aplicaciones, responder incidencias y establecer políticas de seguridad.
      = link_to 'TEMARIO', mastery_cybersecurity_path, class: 'btn btn-xs btn-primary'
  / .row.second
  /   .col-md-4.center
  /     h5.lighter Mastery Program
  /     h3 Microservicios
  /     p Aprende a reestructurar arquitecturas monolíticas en servicios que intercambian datos entre sí mediante REST APIs.
  /     = link_to 'TEMARIO', 'https://cerouno.typeform.com/to/OhB7O5', class: 'btn btn-xs btn-primary'
  /   .col-md-4.center
  /     h5.lighter Mastery Program
  /     h3 Digital Leadership
  /     p Aprende a detectar oportunidades de mercado, desarrollar productos digitales y crear estrategias de ventas y distribución.
  /     = link_to 'TEMARIO', 'https://cerouno.typeform.com/to/OhB7O5', class: 'btn btn-xs btn-primary'
  /   .col-md-4.center
  /     h5.lighter Mastery Program
  /     h3 Scrum
  /     p Aprende a comunicar valor a tus clientes y a manejar equipos en ciclos de desarrollo corto con la metodología Scrum.
  /     = link_to 'TEMARIO', 'https://cerouno.typeform.com/to/OhB7O5', class: 'btn btn-xs btn-primary'
= render 'layouts/testimony', quote: @quote_b
= render 'layouts/instructors'

app/views/layouts/_facebook.html.slim
/! Facebook Pixel Code
javascript:
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  | n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  | n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  | t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  | document,'script','https://connect.facebook.net/en_US/fbevents.js');
  | fbq('init', '1598763777088669', {
  | em: 'insert_email_variable'
  | });
  | fbq('track', 'PageView');
noscript
  img height="1" src="https://www.facebook.com/tr?id=1598763777088669&ev=PageView&noscript=1" style="display:none" width="1" /
/! DO NOT MODIFY
/! End Facebook Pixel Code

app/views/layouts/_fontawesome.html.slim
script src="https://kit.fontawesome.com/56d102e60a.js"

app/views/layouts/_footer.html.slim
.footer
  .row
    .col-md-4
      p= link_to 'Aviso de Privacidad', privacy_path
      p= link_to 'Términos y Condiciones', terms_path
    .col-md-8
      p CeroUno Ventures SAPI de CV © 2017-2020 Todos los Derechos Reservados
      p Hecho en Monterrey, NL, México

app/views/layouts/_google.html.slim
script[async src="https://www.googletagmanager.com/gtag/js?id=UA-117329703-1"]
script
  |  window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-117329703-1'); 

app/views/layouts/_hubspot.html.slim
script#hs-script-loader[type="text/javascript" async defer src="//js.hs-scripts.com/4345635.js"]